version: '3.9'
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'contrasena123'
      MYSQL_DATABASE: 'sistema_ecommerce'
      MYSQL_USER: 'hemish'
      MYSQL_PASSWORD: 'contrasena123'
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql  
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80